version: '3.6'

services:
  directus:
    container_name: vgu-website-directus-v3
    image: directus/directus:latest
    expose:
      - "8055"
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
      - ./snapshots:/directus/snapshots
    environment:
      KEY: "replace-with-random-value"
      SECRET: "replace-with-random-value"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "abc123"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: "true"
    networks:
      - new-vgu-network
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://directus:8055/server/health || exit 1
      start_period: 15s
      interval: 15s
      timeout: 15s
      retries: 1
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-intern-v2
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      directus:
        condition: service_healthy
    networks:
      - new-vgu-network
networks:
  new-vgu-network:
    driver: bridge